apiVersion: v1
kind: Service
metadata:
  name: ms-payment-service
  labels:
    app: ms-payment-service
spec:
  selector:
    app: ms-payment-service
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: ClusterIP
